spring.temporal:
  host: temporalio-prod-frontend.temporalio
  port: 7233
  useSsl: false
  createWorkers: true
  workflowDefaults:
    executiontimeout: 1000
    executiontimeoutUnit: SECONDS
    activityPoolSize: 100
    workflowPoolSize: 50
  workflows:
    ReiseBuchung:
      taskQueue: ReiseBuchung