apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reise-buchung

resources:
  - namespace.yaml

bases:
  - ../reise-buchung/k8s/base
  - ../hotel-service/k8s/base
  - ../flug-service/k8s/base